package:
  name: hqm
  version: "0.0.5"

source:
  path: ./

build:
  number: 0
  script: "$PYTHON -m pip install ."
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python==3.9.17
    - numpy==1.23.5, 
    - pennylane==0.28.0

test:
  imports:
    - hqm

about:
  home: https://github.com/alessandrosebastianelli/hybrid_quantum_models/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Hybrid Quantum Models - HQM"